#!/usr/bin/env bash

if [ "$(id -u)" != 0 ]; then
  echo "Root permissions required" >&2
  exit 1
fi

file="/var/users"
oldIFS=$IFS

create_user() {

IFS=$oldIFS

groupadd "$group"

if [ "$group" = "it" ] || [ "$group" = "security" ]; then
  if ! grep -q "%$group" /etc/sudoers; then
    cp /etc/sudoers{,.bkp}
    echo "%$group ALL=(ALL) ALL" >> /etc/sudoers
  fi
  shell="/bin/bash"
fi

mkdir "/home/$group"
useradd "$user" -g "$group" -b "/home/$group" -s "$shell"
}


if [ ! -z "$2" ]; then
  user="$1"
  group="$2"
  echo "Username: $user Group: $group"
  create_user
elif [ -f "$file" ]; then
  IFS=$'\n'
  for line in $(cat "$file"); do
    user=$(echo "$line" | cut -d' ' -f1)
    group=$(echo "$line" | cut -d' ' -f2)
    echo "Username: $user Group: $group"
    create_user
  done
else
  echo "Welcome!"
  select option in "Add user" "Show users" "Exit"
  do case $option in
	"Add user")
  		   read -p "Enter username: " user
  		   read -p "Enter groupname: " group
  		   create_user ;;

	"Show users")
		   cut -d: -f1 /etc/passwd ;;

	"Exit")
		   break ;;
	*) echo Wrong option ;;
     esac
  done

fi
