- name: Apply my_user_role to manage users on localhost
  hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - role: my_user_role
      vars:
        users_list:
          - name: alice
            password: "{{ '*' | password_hash('*') }}"
            groups: "admin"
            ssh_key: "ssh-rsa AAAAB3Nza... alice@myserver"
            state: present
          - name: bob
            state: absent
